In [1]:
import pandas as pd

In [2]:
aggr = pd.read_csv('cluster_aggregates.csv')
aggr.head()

,Unnamed: 0,kmeans_119,moving_time,average_watts,suffer_score,ride_count
0,0,0,6776.846154,113.815385,82.153846,13
1,1,1,2048.645161,86.200000,25.806452,31
2,2,2,10094.000000,126.872727,65.414581,11
3,3,3,2204.875000,135.349603,33.853645,8
4,4,4,4053.000000,127.427273,68.037689,11

In [3]:
aggr.describe()

,Unnamed: 0,kmeans_119,moving_time,average_watts,suffer_score,ride_count
count,119.000000,119.000000,119.000000,119.000000,119.000000,119.000000
mean,59.000000,59.000000,5578.134597,137.794923,68.267114,12.075630
std,34.496377,34.496377,2559.163573,23.807952,21.072001,5.542073
min,0.000000,0.000000,1000.333333,80.923333,9.000000,1.000000
25%,29.500000,29.500000,3770.110909,125.687917,63.875000,9.000000
50%,59.000000,59.000000,5000.615385,139.109091,65.414581,11.000000
75%,88.500000,88.500000,7405.731618,155.655556,71.968750,14.000000
max,118.000000,118.000000,14002.555556,186.566667,141.500000,31.000000

In [5]:
pre_train = aggr[['moving_time', 'ride_count']]
pre_train.head()

    moving_time  ride_count
0   6776.846154          13
1   2048.645161          31
2  10094.000000          11
3   2204.875000           8
4   4053.000000          11

In [14]:
mean_avg_watts = aggr['average_watts'].mean()
mean_suffer_score = aggr['suffer_score'].mean()
pre_train.loc[:, 'average_watts'] = aggr['average_watts'].apply(lambda x : 1 if x >= mean_avg_watts else 0)
pre_train.loc[:, 'suffer_score'] = aggr['suffer_score'].apply(lambda x : 1 if x >= mean_suffer_score else 0)
pre_train.describe()

        moving_time  ride_count  average_watts  suffer_score
count    119.000000  119.000000     119.000000    119.000000
mean    5578.134597   12.075630       0.521008      0.310924
std     2559.163573    5.542073       0.501671      0.464829
min     1000.333333    1.000000       0.000000      0.000000
25%     3770.110909    9.000000       0.000000      0.000000
50%     5000.615385   11.000000       1.000000      0.000000
75%     7405.731618   14.000000       1.000000      1.000000
max    14002.555556   31.000000       1.000000      1.000000

In [25]:
pre_train.head()
pre_train.to_csv('pre_classification_pre_plan.csv')

In [33]:
pre_train_plan = pre_train[['moving_time', 'ride_count']]
pre_train_plan.loc[:, 'training_plan'] = pre_train['average_watts'].astype(str).str.cat(pre_train['suffer_score'].astype(str), sep='_')
pre_train_plan.to_csv('pre_classification.csv')
pre_train_plan.head()

/var/folders/ph/n1bcmp_s2rlgrd9vg896nks80000gn/T/ipykernel_24727/4034469462.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pre_train_plan.loc[:, 'training_plan'] = pre_train['average_watts'].astype(str).str.cat(pre_train['suffer_score'].astype(str), sep='_')

    moving_time  ride_count training_plan
0   6776.846154          13           0_1
1   2048.645161          31           0_0
2  10094.000000          11           0_0
3   2204.875000           8           0_0
4   4053.000000          11           0_0

In [38]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def train_test_classifiers(df):
    # Assuming 'training_plan' is your target variable
    X = df[['moving_time', 'ride_count']]
    y = df['training_plan']

    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Standardize the features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Initialize classifiers
    classifiers = {
        'Logistic Regression': LogisticRegression(),
        'Decision Tree': DecisionTreeClassifier(),
        'Random Forest': RandomForestClassifier(),
        'Support Vector Machine': SVC(),
        'K-Nearest Neighbors': KNeighborsClassifier()
    }

    # Train and test each classifier
    for name, clf in classifiers.items():
        clf.fit(X_train_scaled, y_train)
        y_pred = clf.predict(X_test_scaled)

        # Evaluate the classifier
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, average='micro')
        recall = recall_score(y_test, y_pred, average='micro')
        f1 = f1_score(y_test, y_pred, average='micro')
        conf_matrix = confusion_matrix(y_test, y_pred)

        # Display results
        print(f"\nClassifier: {name}")
        print(f"Accuracy: {accuracy:.4f}")
        print(f"Precision: {precision:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"F1 Score: {f1:.4f}")
        print(f"Confusion Matrix:\n{conf_matrix}")

In [39]:
train_test_classifiers(pre_train_plan)

Classifier: Logistic Regression
Accuracy: 0.4583
Precision: 0.4583
Recall: 0.4583
F1 Score: 0.4583
Confusion Matrix:
[[4 0 3 0]
 [1 0 3 0]
 [1 0 7 0]
 [2 0 3 0]]

Classifier: Decision Tree
Accuracy: 0.2500
Precision: 0.2500
Recall: 0.2500
F1 Score: 0.2500
Confusion Matrix:
[[2 1 3 1]
 [1 0 1 2]
 [2 2 3 1]
 [0 1 3 1]]

Classifier: Random Forest
Accuracy: 0.3750
Precision: 0.3750
Recall: 0.3750
F1 Score: 0.3750
Confusion Matrix:
[[3 1 2 1]
 [1 0 1 2]
 [1 1 4 2]
 [1 0 2 2]]

Classifier: Support Vector Machine
Accuracy: 0.4583
Precision: 0.4583
Recall: 0.4583
F1 Score: 0.4583
Confusion Matrix:
[[4 0 3 0]
 [0 0 0 4]
 [0 0 5 3]
 [2 0 1 2]]

Classifier: K-Nearest Neighbors
Accuracy: 0.3333
Precision: 0.3333
Recall: 0.3333
F1 Score: 0.3333
Confusion Matrix:
[[3 1 3 0]
 [1 0 1 2]
 [2 0 4 2]
 [2 1 1 1]]