In [2]:
import json

In [6]:
basic_athlete_info = json.loads('''{
    "id": 3506416,
    "username": "rhish_hatt",
    "resource_state": 2,
    "firstname": "Rhish",
    "lastname": "Hatt",
    "bio": "ASU Grad Student üî± üö¥‚Äç‚ôÇÔ∏è",
    "city": "Tempe",
    "state": "Arizona",
    "country": "United States",
    "sex": "M",
    "premium": true,
    "summit": true,
    "created_at": "2013-12-17T14:40:20Z",
    "updated_at": "2023-09-18T01:41:06Z",
    "badge_type_id": 1,
    "weight": 79.0,
    "profile_medium": "https://dgalywyr863hv.cloudfront.net/pictures/athletes/3506416/1139281/30/medium.jpg",
    "profile": "https://dgalywyr863hv.cloudfront.net/pictures/athletes/3506416/1139281/30/large.jpg",
    "friend": null,
    "follower": null
}''')

print(basic_athlete_info)

{'id': 3506416, 'username': 'rhish_hatt', 'resource_state': 2, 'firstname': 'Rhish', 'lastname': 'Hatt', 'bio': 'ASU Grad Student üî± üö¥\u200d‚ôÇÔ∏è', 'city': 'Tempe', 'state': 'Arizona', 'country': 'United States', 'sex': 'M', 'premium': True, 'summit': True, 'created_at': '2013-12-17T14:40:20Z', 'updated_at': '2023-09-18T01:41:06Z', 'badge_type_id': 1, 'weight': 79.0, 'profile_medium': 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/3506416/1139281/30/medium.jpg', 'profile': 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/3506416/1139281/30/large.jpg', 'friend': None, 'follower': None}

In [18]:
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

auth_url = "https://www.strava.com/oauth/token"
activites_url = "https://www.strava.com/api/v3/athlete/activities"
access_token = "bdf53f4dad1073eb68c4a8451ee17efddb73e466"
header = {'Authorization': 'Bearer ' + access_token}
full_dataset = []
page = 1

while True:
    param = {'per_page': 200, 'page': page}
    page_dataset = requests.get(activites_url, headers=header, params=param).json()
    if len(page_dataset) == 0:
        break
    page += 1
    full_dataset.extend(page_dataset)

print(len(full_dataset))

1586

In [28]:
import pickle

with open('strava_data_python_dict.pickle', 'wb') as data_pickle:
    pickle.dump(full_dataset, data_pickle, protocol=pickle.HIGHEST_PROTOCOL)

In [30]:
json.dumps(full_dataset[2])

'{"resource_state": 2, "athlete": {"id": 3506416, "resource_state": 1}, "name": "AZ State ITT - 7th/11 in Men Merckx - destroyed by the headwind", "distance": 39964.1, "moving_time": 4020, "elapsed_time": 4020, "total_elevation_gain": 42.0, "type": "Ride", "sport_type": "Ride", "workout_type": 11, "id": 9912737242, "start_date": "2023-09-24T14:45:58Z", "start_date_local": "2023-09-24T07:45:58Z", "timezone": "(GMT-07:00) America/Phoenix", "utc_offset": -25200.0, "location_city": null, "location_state": null, "location_country": "United States", "achievement_count": 0, "kudos_count": 25, "comment_count": 6, "athlete_count": 3, "photo_count": 0, "map": {"id": "a9912737242", "summary_polyline": "ykgfEhyzfTbUw\\\\xAsB~AqB~`@se@j_@qc@pCwCpDeDdiAc}@~L}Jpi@ob@rO_MbHsFrIaHxk@od@tDuCfLgJxMgKpJyHbKaIz[gWnAaAdAs@lAo@jCoAdAq@|I_HlQqNbA}@fBkB~BuCd@g@|A{AnDqCbEwCrPuMnWwShM{J~c@a^rXiTrIaHhY}T|VeS|KuIvl@me@vEoDrQuNzDyC`r@wi@vFqEb^}XzEyDlVmRdBgAbFkCtCmBbZoUJOAECAEB_\\\\dWwChBmDhBkAp@gAx@cDfCql@de@o`@|ZeVpRaLvIaw@~m@yAfAkM`K{RrO_F~DyB`BwYjUufAd{@{TdQiB|A}GjFyYpU{EtDoBpAmCpBkB~Ao@l@o@t@sBjCsCrC}StPaHlF{@h@qEzBwBvAgCnB{n@dg@}XrTkH~FuIxGqgBxvAgOnLiMdK}SjP}l@te@oDdDuCzCsSdVol@pr@aC~CmBnCkSnZ", "resource_state": 2}, "trainer": false, "commute": false, "manual": false, "private": false, "visibility": "everyone", "flagged": false, "gear_id": "b12532853", "start_latlng": [32.64717631973326, -111.38980829156935], "end_latlng": [32.647236585617065, -111.38979689218104], "average_speed": 9.941, "max_speed": 15.096, "average_cadence": 86.7, "average_temp": 22, "average_watts": 249.9, "max_watts": 731, "weighted_average_watts": 249, "kilojoules": 1004.5, "device_watts": true, "has_heartrate": true, "average_heartrate": 175.6, "max_heartrate": 185.0, "heartrate_opt_out": false, "display_hide_heartrate_option": true, "elev_high": 583.6, "elev_low": 536.4, "upload_id": 10624071939, "upload_id_str": "10624071939", "external_id": "garmin_ping_296207949248", "from_accepted_tag": false, "pr_count": 0, "total_photo_count": 6, "has_kudoed": false, "suffer_score": 211.0}'

In [31]:
import pandas as pd

df = pd.DataFrame(full_dataset)

In [34]:
df.head()

,resource_state,athlete,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,...,elev_high,elev_low,upload_id,upload_id_str,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,suffer_score
0,2,"{'id': 3506416, 'resource_state': 1}",Lunch Ride,3564.2,723,830,3.0,Ride,Ride,NaN,...,355.6,348.4,1.062527e+10,10625272364,garmin_ping_296232055012,False,0,0,False,3.0
1,2,"{'id': 3506416, 'resource_state': 1}",Morning Ride,4904.7,1355,1355,3.0,Ride,Ride,NaN,...,545.0,534.4,1.062426e+10,10624263906,garmin_ping_296211250274,False,0,0,False,5.0
2,2,"{'id': 3506416, 'resource_state': 1}",AZ State ITT - 7th/11 in Men Merckx - destroye...,39964.1,4020,4020,42.0,Ride,Ride,11.0,...,583.6,536.4,1.062407e+10,10624071939,garmin_ping_296207949248,False,0,6,False,211.0
3,2,"{'id': 3506416, 'resource_state': 1}",Morning Ride,2744.7,427,427,1.0,Ride,Ride,NaN,...,522.0,519.4,1.062350e+10,10623497643,garmin_ping_296198158652,False,0,0,False,2.0
4,2,"{'id': 3506416, 'resource_state': 1}",New tyre testing,29299.1,4662,5821,52.0,Ride,Ride,10.0,...,421.0,384.0,1.061218e+10,10612179069,garmin_ping_295937594218,False,2,1,False,42.0

In [35]:
df.tail()

,resource_state,athlete,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,...,elev_high,elev_low,upload_id,upload_id_str,external_id,from_accepted_tag,pr_count,total_photo_count,has_kudoed,suffer_score
1581,2,"{'id': 3506416, 'resource_state': 1}",Morning quickie,21360.6,3429,4037,193.1,Ride,Ride,NaN,...,663.2,551.4,111431783.0,111431783,12448D74-ED27-4042-9DE9-37F3088E19DC,False,4,0,False,NaN
1582,2,"{'id': 3506416, 'resource_state': 1}",Necklace loop with arai,24106.3,3704,4795,297.9,Ride,Ride,NaN,...,670.1,567.9,111131538.0,111131538,33E0CC5C-C67F-4F32-ACFF-210DED039CE5,False,5,0,False,NaN
1583,2,"{'id': 3506416, 'resource_state': 1}",Morning Ride,22477.9,3159,3159,265.0,Ride,Ride,NaN,...,663.8,584.3,110982840.0,110982840,D8D93A54-F378-49D9-BA2C-9FD6C4879555,False,1,0,False,NaN
1584,2,"{'id': 3506416, 'resource_state': 1}",Morning Ride,18113.8,2695,2695,183.0,Ride,Ride,NaN,...,663.3,584.1,110454042.0,110454042,EEA2B8D9-1CBC-44E0-8C0B-E665DECC38EC,False,0,0,False,NaN
1585,2,"{'id': 3506416, 'resource_state': 1}",Morning Ride,18797.8,2510,2510,174.5,Ride,Ride,NaN,...,664.2,567.8,110156907.0,110156907,9E9074B0-AC14-4332-90BB-9262CDF8971F,False,0,0,False,NaN